[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  framework = "#custom"
